version: 2

models:
  - name: stg_customers
    description: "Cleans and standardizes customer data from the raw seed"
    columns:
      - name: customer_id
        description: "Unique identifier for each customer"
        tests:
          - not_null
          - unique
      - name: name
        description: "Full name of the customer"
      - name: email
        description: "Customer email address"
      - name: signup_date
        description: "Date the customer signed up"
      - name: region
        description: "Customer’s region"

  - name: stg_orders
    description: "Cleans and standardizes order data with correct types and naming"
    columns:
      - name: order_id
        description: "Unique identifier for each order"
        tests:
          - not_null
          - unique
      - name: customer_id
        description: "Foreign key to the customer"
        tests:
          - not_null
      - name: product_id
        description: "Foreign key to the product"
        tests:
          - not_null
      - name: order_date
        description: "Date the order was placed"
        tests:
          - not_null
      - name: quantity
        description: "Number of units purchased"
      - name: order_amount
        description: "Total order amount in USD"

  - name: stg_products
    description: "Standardizes product information from seed data"
    columns:
      - name: product_id
        description: "Unique product identifier"
        tests:
          - not_null
          - unique
      - name: product_name
        description: "Name of the product"
      - name: category
        description: "Product category"
      - name: price
        description: "Unit price of the product"
