version: 2

models:
  - name: stg_customers
    description: "Cleans and standardizes customer data from the raw seed"
    columns:
      - name: customer_id
        description: "Unique identifier for each customer"
        tests:
          - not_null
          - unique
      - name: email
        description: "Customer email address"

  - name: stg_orders
    description: "Standardizes order data with type-casting and renaming"
    columns:
      - name: order_id
        tests:
          - not_null
          - unique
      - name: customer_id
        tests:
          - not_null
      - name: product_id
        tests:
          - not_null
      - name: order_date
        tests:
          - not_null

  - name: stg_products
    description: "Product dimension cleaned from the product seed file"
    columns:
      - name: product_id
        tests:
          - not_null
          - unique
      - name: product_name
      - name: category

